src/BrightonSausageCoEcomms/Controllers/ClientsSuppliersController.cs
using System.Web.Mvc;

namespace BrightonSausageCoEcomms.Controllers
{
    public class ClientsSuppliersController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/BrightonSausageCoEcomms/Views/Shared/DisplayTemplates/AdminHeader.cshtml
<div id="logo"><a href="#">
    <img src="~/assets/images/logo.png" alt="Brighton Sausage Co., Est. 2006" border="0" /></a></div>
<div id="top">
    <div id="navsection">
        <div id="baskettemp">&nbsp;</div>

        @*<div id="basketbox">
            <div id="basket"><a href="#">
                <img src="~/assets/images/basket.jpg" alt="Basket" border="0" /></a></div>
            <div id="viewbasket"><a href="#">View Basket</a></div>
            <div id="numitems">5 Items</div>
            <div id="basketboxtotal">&pound;19.00</div>
            <div id="checkoutbtn"><a href="#">
                <img src="~/assets/images/checkout.png" alt="CHECKOUT" border="0" /></a></div>
        </div>*@
        @Html.Partial("DisplayTemplates/Navigation")
        
        @RenderSection("AdminSubNav", true)

    </div>
</div>
<!-- /top -->

src/BrightonSausageCoEcomms/Views/Shared/DisplayTemplates/Basket.cshtml
<div class="row pull-right span5 offset4">
    <ul class="nav nav-pills">
        <li><a href="#">View Basket</a></li>
        <li><a href="#">5 Items</a></li>
        <li><a href="#">£11.00</a></li>
        <li><a href="#">Checkout</a></li>
    </ul>
</div>

src/BrightonSausageCoEcomms/Views/Shared/DisplayTemplates/Footer.cshtml
@{
    var version = typeof(BrightonSausageCoEcomms.MvcApplication).Assembly.GetName().Version;
}
<!-- FOOTER -->
<div id="footer">
    <div id="footercontent">
        <div id="footerleft">
            @Html.Partial("DisplayTemplates/Navigation")
            <p class="footerdetails"><a href="#">Terms &amp; Conditions</a> &ndash; <a href="#">Privacy Policy</a> &ndash; Copyright Brighton Sausage Co. &copy; 2012</p>
        </div>
        <!-- /footerleft -->

        <div id="footerright">
            version: @version
        </div>
        <!-- /footerright -->
    </div>
    <!-- /footercontent -->
</div>
<!-- /footer -->

src/BrightonSausageCoEcomms/Views/Shared/DisplayTemplates/Header.cshtml
<div id="logo"><a href="">
    <img src="~/assets/images/logo.png" alt="Brighton Sausage Co., Est. 2006" border="0" /></a></div>
<div id="top">
    <div id="navsection">
        <div id="basketbox">
            <div id="basket"><a href="">
                <img src="~/assets/images/basket.jpg" alt="Basket" border="0" /></a></div>
            <div id="viewbasket"><a href="">View Basket</a></div>
            <div id="numitems">5 Items</div>
            <div id="basketboxtotal">&pound;19.00</div>
            <div id="checkoutbtn"><a href="">
                <img src="~/assets/images/checkout.png" alt="CHECKOUT" border="0" /></a></div>
        </div>
        <div id="nav">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Products", "Index", "Products")</li>
                <li>@Html.ActionLink("Clients/Suppliers", "Index", "ClientsSuppliers")</li>
                <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                <li>@Html.ActionLink("About", "Index", "About")</li>
                <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
            </ul>
        </div>

    </div>
</div>
<!-- /top -->

src/BrightonSausageCoEcomms/Views/Shared/DisplayTemplates/Navigation.cshtml
<div class="nav" id="nav">
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Products", "Index", "Products")</li>
        <li>@Html.ActionLink("Clients/Suppliers", "Index", "ClientsSuppliers")</li>
        <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
        <li>@Html.ActionLink("About", "Index", "About")</li>
    </ul>
</div>

src/BrightonSausageCoEcomms/Views/Shared/DisplayTemplates/ProductCategoriesNavigation.cshtml
@model List<BrightonSausageCoEcomms.Infrastructure.Models.Category>
<div id="left">
    <div class="leftmenu leftmenufirst">
        <p class="leftmenutext">
            <a href="#" id="">
                <img src="~/assets/images/refine.jpg" alt="REFINE RESULTS" border="0" /></a>
        </p>
        <p class="leftmenuarrow">
            <a href="#" id="">
                <img src="~/assets/images/expand.jpg" alt="" border="0" /></a>
        </p>
    </div>
    <!-- /leftmenu -->
    <div class="leftmenu">
        <p class="leftmenutext">
            <a href="#" id="">
                <img src="~/assets/images/browse.jpg" alt="BROWSE SHOP" border="0" /></a>
        </p>
        <p class="leftmenuarrow">
            <a href="#" id="">
                <img src="~/assets/images/collapse.jpg" alt="" border="0" /></a>
        </p>
    </div>
    <!-- /leftmenu -->
    <div class="leftmenuresults" id="">
        <ul>
            @for (int i = 0; i < Model.Count; i++)
            {
                if (i % 2 == 0)
                {
                <li>@Html.ActionLink(Model[i].Name, "Index", "Products", new { categoryFilter = Model[i].Name }, new { @class = "stripe" })</li>
                }
                else
                {
                <li>@Html.ActionLink(Model[i].Name, "Index", "Products", new { categoryFilter = Model[i].Name }, null)</li>
                }
            }
        </ul>
    </div>
    <!-- /leftmenuresults -->
    <div id="shorthr"></div>

    <!-- TESTIMONIALS -->
    <div id="smallboxtop"></div>
    <div id="smallbox">
        <div id="testimonial">
            <p class="test">
                GREAT VARIETY...<br />
                BEST SAUSAGES I HAVE<br />
                EVER TASTED!
            </p>
            <div id="dottedhr"></div>
            <p class="more">
                <a href="#">
                    <img src="~/assets/images/findoutmore.jpg" alt="FIND OUT MORE" border="0" /></a>
            </p>
        </div>
    </div>
    <div id="smallboxbottom"></div>
    <!-- /TESTIMONIALS -->
</div>
<!-- /left -->